//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoiMatKhau
    {
        public string TenDangNhap { get; set; }
        public string TenHienThi { get; set; }
        public string MatKhauCu { get; set; }
        public string MatKhauMoi { get; set; }
        public string NhapLaiMatKhau { get; set; }
    }
}
