//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyNhanSuEntities : DbContext
    {
        public QuanLyNhanSuEntities()
            : base("name=QuanLyNhanSuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoHiem> BaoHiems { get; set; }
        public virtual DbSet<BoPhan> BoPhans { get; set; }
        public virtual DbSet<ChamCong> ChamCongs { get; set; }
        public virtual DbSet<DangKy> DangKies { get; set; }
        public virtual DbSet<DoiMatKhau> DoiMatKhaus { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<HoSoNhanVien> HoSoNhanViens { get; set; }
        public virtual DbSet<KhenThuong> KhenThuongs { get; set; }
        public virtual DbSet<KyLuat> KyLuats { get; set; }
        public virtual DbSet<LamThemGio> LamThemGios { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<LuongNhanVien> LuongNhanViens { get; set; }
        public virtual DbSet<NhanVienDiTre> NhanVienDiTres { get; set; }
        public virtual DbSet<ThaiSan> ThaiSans { get; set; }
        public virtual DbSet<ThamNienNhanVien> ThamNienNhanViens { get; set; }
        public virtual DbSet<TinhLuong> TinhLuongs { get; set; }
    }
}
